import { SubtitleSegment } from '../types';

export interface YouTubeCaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface YouTubeCaptionResult {
  videoId: string;
  title: string;
  canonicalUrl: string;
  duration: number;
  thumbnailUrl?: string;
  selectedTrack: YouTubeCaptionTrack;
  tracks: YouTubeCaptionTrack[];
  segments: SubtitleSegment[];
}

export async function fetchYouTubeCaptions(
  url: string,
  preferredLanguage?: string,
): Promise<YouTubeCaptionResult> {
  const response = await fetch('/api/youtube-captions', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ url, preferredLanguage }),
  });

  const data = await response.json().catch(() => null);

  if (!response.ok) {
    throw new Error(data?.error || `Failed to fetch YouTube captions (${response.status})`);
  }

  return data as YouTubeCaptionResult;
}
