import { extractVideoId, fetchYouTubeTranscript } from '../utils/youtubeTranscript';

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const body = typeof req.body === 'string' ? JSON.parse(req.body) : (req.body || {});
    const { url, preferredLanguage } = body;

    if (!url || typeof url !== 'string') {
      return res.status(400).json({ error: 'Missing YouTube URL' });
    }

    const videoId = extractVideoId(url);
    if (!videoId) {
      return res.status(400).json({ error: 'Invalid YouTube URL' });
    }

    const preferredLangs = preferredLanguage
      ? [preferredLanguage.toLowerCase(), 'zh', 'en']
      : ['zh', 'en'];

    const result = await fetchYouTubeTranscript(videoId, preferredLangs);

    const canonicalUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const videoDetails = result.videoDetails;

    return res.status(200).json({
      videoId,
      title: videoDetails.title || `YouTube ${videoId}`,
      canonicalUrl,
      duration: Number(videoDetails.lengthSeconds || result.segments[result.segments.length - 1]?.endTime || 0),
      thumbnailUrl: videoDetails.thumbnail?.thumbnails?.slice(-1)?.[0]?.url,
      selectedTrack: {
        languageCode: result.languageCode,
        name: result.language,
        isAutoGenerated: false,
      },
      tracks: [],
      segments: result.segments,
    });
  } catch (error) {
    console.error('[YouTube Captions] Error:', error);
    const message = error instanceof Error ? error.message : 'Failed to import YouTube captions';

    if (message.includes('No captions')) {
      return res.status(404).json({ error: 'No captions found for this video.' });
    }
    if (message.includes('unavailable')) {
      return res.status(404).json({ error: 'Video unavailable or region-restricted.' });
    }
    if (message.includes('Bot detected') || message.includes('IP blocked')) {
      return res.status(429).json({ error: 'Request blocked by YouTube. Please try again later.' });
    }

    return res.status(500).json({ error: message });
  }
}
